version: '3.8'
services:
  todo:
    networks:
      - backend
    container_name: todo
    build: 
      context: .
      dockerfile: ./docker/dockerfile.todo-service
    image: todo-service
    volumes:
      - .:/usr/src/app:rw
    ports:
      - "8081:8081"
    environment:
      - OTEL_SDK_DISABLED=false
      - NODE_ENV=staging
      - CODE_VERSION=${VERSION}
    x-develop:
      watch:
        - action: sync
          path: ./src/todo-service.ts
          target: /usr/src/app
#        - action: rebuild
#          path: package.json
  auth:
    networks:
      - backend
    container_name: auth
    build: 
      context: .
      dockerfile: ./docker/dockerfile.auth-service
    image: auth-service
    volumes:
      - .:/usr/src/app:rw
    environment:
      - NODE_ENV=staging
      - CODE_VERSION=${VERSION}
    x-develop:
      watch:
        - action: sync
          path: ./src/auth-service.ts
          target: /usr/src/app
        - action: rebuild
          path: package.json
  redis:
    networks:
      - backend
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
  redis-commander:
    networks:
      - backend
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8088:8081"
  jaeger:
    networks:
      - backend
    image: jaegertracing/all-in-one
    ports:
      - "4318"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: true
networks:
  backend:
