FROM node:16.20.2

ENV USER_VARIABLE=mama

LABEL "com.example.vendor"="thoschu" \
      "com.example.version"="2.0"

WORKDIR /usr/src/app

COPY ./package.json ./

RUN yarn

EXPOSE 8082

CMD ["yarn", "auth"]
