receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/servicegraphprocessor
  batch:
  batch/2:
    send_batch_size: 10000
    timeout: 10s
  resource:
    attributes:
      - key: cloud.availability_zone
        value: "zone-1"
        action: upsert # insert if not exists, update otherwise
      - key: k8s.cluster.name
        from_attribute: k8s-cluster
        action: insert # insert if not exists, do nothing otherwise
      - key: redundant-attribute
        action: delete # delete if exists
exporters:
  debug:
  prometheus:
    endpoint: "0.0.0.0:8889"
    send_timestamps: true
    namespace: otel
    const_labels:
      via: collector
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
    tls:
      insecure: true
extensions:
  health_check:
  pprof:
  zpages:
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, otlp/jaeger, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch/2]
      exporters: [debug, prometheus]
