extensions:
  oidc:
  basicauth/server:
    htpasswd:
      inline: |
        tom:password
  basicauth/client:
    client_auth:
      username: username
      password: password
  bearertokenauth:
    token: "randomtoken"
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  otlp/auth:
    protocols:
      http:
        endpoint: 0.0.0.0:4316
        auth:
          authenticator: basicauth/server
      grpc:
        endpoint: 0.0.0.0:4315
        auth:
          authenticator: bearertokenauth
processors:
  batch:
exporters:
  logging:
    loglevel: debug
  debug: # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  prometheus:
    endpoint: "0.0.0.0:8889"
    send_timestamps: true
    namespace: otel
    const_labels:
      via: collector
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
    tls:
      insecure: true
service:
  extensions: [basicauth/server]
  telemetry:
    logs:
        level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
